{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}
{-# HLINT ignore "Use camelCase" #-}

module MainApp where

import Miso
    ( component
    , App
    , text
    )
import Miso.Html
    ( div_
    )
import Data.Text (Text)
import qualified Data.ByteString.Base64 as B64
import Data.ByteString ( ByteString, fromStrict )
import Data.Text.Encoding  (encodeUtf8)
import Data.Aeson (decode)

import Types (PostPart, Site(..))
import PostPartRender (render)

base64_encoded_json_example :: Text
-- base64_encoded_json_example = "W3siY29udGVudHMiOiLwn5e9IiwidGFnIjoiU2ltcGxlVGV4dCJ9LHsiY29udGVudHMiOlt7ImNvbnRlbnRzIjoiVU5JVEVEIFNUQVRFUyBQT0xJVElDUyAiLCJ0YWciOiJTaW1wbGVUZXh0In1dLCJ0YWciOiJSZWRUZXh0In0seyJjb250ZW50cyI6IvCfpoUiLCJ0YWciOiJTaW1wbGVUZXh0In0seyJ0YWciOiJTa2lwIn0seyJjb250ZW50cyI6W3sidGFnIjoiU2tpcCJ9LHsiY29udGVudHMiOiI8QmVuIEZyYW5rbGluIEVkaXRpb24iLCJ0YWciOiJTaW1wbGVUZXh0In1dLCJ0YWciOiJPcmFuZ2VUZXh0In0seyJ0YWciOiJTa2lwIn0seyJ0YWciOiJTa2lwIn0seyJjb250ZW50cyI6IlRocmVhZCBmb3IgdGhlIGhlbGxpc2ggZGlzY3Vzc2lvbiByZWxhdGVkIHRvICIsInRhZyI6IlNpbXBsZVRleHQifSx7ImNvbnRlbnRzIjpbeyJjb250ZW50cyI6InRoZSBzY291cmdlIG9mIHRoZSBlYXJ0aCwgdGhlIGRlc3Ryb3llciBvZiBuYXRpb25zLCB0aGUgZmF0aGVyIG9mIGZhc2Npc20sIHRoZSBlbmFibGVyIG9mIGV0aG5vc3RhdGVzLCB0aGUgdHJlYXRsZXJpdGUgdHlyYW50LCB0aGUgcHJvdGVjdG9yIG9mIHBlZG9waGlsZXMsIHRoZSBleHBvcnRlciBvZiBlY29jaWRlLCB0aGUgY2FwdGFpbiBvZiBjYXBpdGFsaXNtLCB0aGUga2luZyBvZiBjb3VwcywgdGhlIHN1bHRhbiBvZiBzYW5jdGlvbnMsIHRoZSBlbWlyIG9mIHRoZSBlbWJhcmdvLCB0aGUgYXV0b2NyYXQgb2YgYXVzdGVyaXR5LCB0aGUgZG9nZSBvZiBkZXJlZ3VsYXRpb24sIHRoZSBiYXJvbiBvZiBidXN0aW5nIHVuaW9ucywgdGhlIHByaW5jZSBvZiBwcml2YXRpemF0aW9uLCB0aGUgbG9yZCBvZiBsb2FuIHNoYXJrcywgdGhlIHBhdHJvbi1zYWludCBvZiBwcm94eSB3YXJzLCB0aGUgc3BvbnNvciBvZiBzZXR0bGVycywgdGhlIGd1YXJhbnRvciBvZiBnZW5vY2lkZXMsIHRoZSBEaXZpZGVkICRuYWtra2VzIG9mIEFtZXJpa2trYSIsInRhZyI6IlNpbXBsZVRleHQifV0sInRhZyI6Ikl0YWxpY3MifSx7ImNvbnRlbnRzIjoi4oSiIiwidGFnIjoiU2ltcGxlVGV4dCJ9LHsidGFnIjoiU2tpcCJ9LHsidGFnIjoiU2tpcCJ9LHsiY29udGVudHMiOiLwn4+IIPCfkrUg8J+MrSDwn42UIiwidGFnIjoiU2ltcGxlVGV4dCJ9LHsidGFnIjoiU2tpcCJ9LHsidGFnIjoiU2tpcCJ9LHsidGFnIjoiU2tpcCJ9LHsiY29udGVudHMiOiJodHRwczovL3N0cmlrZXRyYWNrZXIuaWxyLmNvcm5lbGwuZWR1LyIsInRhZyI6IlBvc3RlZFVybCJ9LHsidGFnIjoiU2tpcCJ9LHsidGFnIjoiU2tpcCJ9LHsidGFnIjoiU2tpcCJ9LHsiY29udGVudHMiOiJodHRwczovL2dpdGh1Yi5jb20vZGVzc2FsaW5lcy9lc3NheXMvYmxvYi9tYWluL3VzX2F0cm9jaXRpZXMubWQiLCJ0YWciOiJQb3N0ZWRVcmwifSx7InRhZyI6IlNraXAifSx7InRhZyI6IlNraXAifSx7InRhZyI6IlNraXAifSx7ImNvbnRlbnRzIjoiKHNwb25zb3JlZCBieSBVU0FJRCkiLCJ0YWciOiJTaW1wbGVUZXh0In0seyJ0YWciOiJTa2lwIn0seyJjb250ZW50cyI6IuKAoiBDTk46ICIsInRhZyI6IlNpbXBsZVRleHQifSx7ImNvbnRlbnRzIjoiaHR0cHM6Ly93d3cubGl2ZW5ld3Nub3cuY29tL2FtZXJpY2FuL2Nubi1uZXdzLXVzYS5odG1sIiwidGFnIjoiUG9zdGVkVXJsIn0seyJ0YWciOiJTa2lwIn0seyJjb250ZW50cyI6IuKAoiBNU05CQzogIiwidGFnIjoiU2ltcGxlVGV4dCJ9LHsiY29udGVudHMiOiJodHRwczovL3d3dy5saXZlbmV3c25vdy5jb20vYW1lcmljYW4vbXNuYmMuaHRtbCIsInRhZyI6IlBvc3RlZFVybCJ9LHsidGFnIjoiU2tpcCJ9LHsiY29udGVudHMiOiLigKIgRk9YOiAiLCJ0YWciOiJTaW1wbGVUZXh0In0seyJjb250ZW50cyI6Imh0dHBzOi8vd3d3LmxpdmVuZXdzbm93LmNvbS9hbWVyaWNhbi9mb3gtbmV3cy1jaGFubmVsLmh0bWwiLCJ0YWciOiJQb3N0ZWRVcmwifSx7InRhZyI6IlNraXAifSx7ImNvbnRlbnRzIjoi4oCiIEJsb29tYmVyZzogIiwidGFnIjoiU2ltcGxlVGV4dCJ9LHsiY29udGVudHMiOiJodHRwczovL3d3dy5ibG9vbWJlcmcuY29tL2xpdmUvdXMiLCJ0YWciOiJQb3N0ZWRVcmwifSx7InRhZyI6IlNraXAifSx7InRhZyI6IlNraXAifSx7InRhZyI6IlNraXAifSx7ImNvbnRlbnRzIjoiaHR0cHM6Ly93b2tlLm5ldC8iLCJ0YWciOiJQb3N0ZWRVcmwifSx7InRhZyI6IlNraXAifSx7InRhZyI6IlNraXAifSx7InRhZyI6IlNraXAifSx7ImNvbnRlbnRzIjoiaHR0cHM6Ly9lcHN0ZWluc2JsYWNrYm9vay5jb20vIiwidGFnIjoiUG9zdGVkVXJsIn0seyJ0YWciOiJTa2lwIn0seyJ0YWciOiJTa2lwIn0seyJ0YWciOiJTa2lwIn0seyJjb250ZW50cyI6Imh0dHBzOi8vd3d3LnRyYWNrYWlwYWMuY29tLyIsInRhZyI6IlBvc3RlZFVybCJ9LHsidGFnIjoiU2tpcCJ9LHsidGFnIjoiU2tpcCJ9LHsiY29udGVudHMiOiJQcmV2aW91cyBUaHJlYWQ6ICIsInRhZyI6IlNpbXBsZVRleHQifSx7ImNvbnRlbnRzIjp7IlJpZ2h0Ijp7ImJvYXJkTmFtZSI6ImxlZnR5cG9sIiwicG9zdElkIjoyNDgxNjA5LCJ0aHJlYWRJZCI6MjQ4MTYwOX19LCJ0YWciOiJRdW90ZSJ9LHsidGFnIjoiU2tpcCJ9LHsidGFnIjoiU2tpcCJ9LHsidGFnIjoiU2tpcCJ9LHsiY29udGVudHMiOlt7ImNvbnRlbnRzIjoiUmVtZW1iZXIgdG8gZmlsdGVyIG1hc3MgdG9yIGJhaXRlcnMsIGZlZHMsIGFuZCB0cm9sbHMiLCJ0YWciOiJTaW1wbGVUZXh0In1dLCJ0YWciOiJSZWRUZXh0In0seyJ0YWciOiJTa2lwIn0seyJjb250ZW50cyI6W3siY29udGVudHMiOiJOb3QgcmVwb3J0aW5nIGlzIGJvdXJnZW9pcyIsInRhZyI6IlNpbXBsZVRleHQifV0sInRhZyI6IlJlZFRleHQifSx7InRhZyI6IlNraXAifSx7ImNvbnRlbnRzIjpbeyJjb250ZW50cyI6IlZpb2xhdG9ycyB3aWxsIGJlIGxhdW5jaGVkIGZyb20gdHJlYnVjaGV0IiwidGFnIjoiU2ltcGxlVGV4dCJ9XSwidGFnIjoiUmVkVGV4dCJ9XQ=="
-- base64_encoded_json_example = "WwogICAgewogICAgICAgICJjb250ZW50cyI6IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICAgInRhZyI6ICJTa2lwIgogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAiY29udGVudHMiOiAiPEJlbiBGcmFua2xpbiBFZGl0aW9uIiwKICAgICAgICAgICAgICAgICJ0YWciOiAiU2ltcGxlVGV4dCIKICAgICAgICAgICAgfQogICAgICAgIF0sCiAgICAgICAgInRhZyI6ICJPcmFuZ2VUZXh0IgogICAgfQpdCg=="
base64_encoded_json_example = "WwogIHsKICAgICJjb250ZW50cyI6ICI8QmVuIEZyYW5rbGluIEVkaXRpb24iLAogICAgInRhZyI6ICJTaW1wbGVUZXh0IgogIH0KXQo="
-- "

bytestring_json_example :: ByteString
bytestring_json_example =
    case B64.decode (encodeUtf8 base64_encoded_json_example) of
        Left err -> error err
        Right x -> x


all_post_parts :: [ PostPart ]
all_post_parts =
    case decode (fromStrict bytestring_json_example) of
        Just x -> x
        Nothing -> error "PostPart json cannot be decoded!"


app :: App () ()
app = component () (const $ pure ()) $ const $
    div_
        []
        [ text "<Based"
        ]
